### ISSUE TITLE
Mod+` doesn't work for code mark toggle

### ISSUE THREAD

**Issue by drenther** [ProseMirror/prosemirror-example-setup#10]
## Description
`Mod+`` and some other shortcuts just don't work from the keymaps setup while others work seamlessly.

Any reason why it can happen.

## How to reproduce?
Can be tried on the example in the documentation.

## System Details
Tested on - macOS Chrome v - 80.0.3987.163

**Comment by vladmoroz** [comment]
Also noticed this problem. @drenther curious what other shortcuts aren't working?

**Comment by marijnh** [comment]
Are you using a keyboard layout where typing a backtick involves shift? (This seems fine on Chrome Linux, didn't get a chance to test in macOS yet.)

**Comment by drenther** [comment]
I tested in macOS. So that might be the case.

**Comment by marijnh** [comment]
You still didn't tell me which keyboard layout you're using and whether backticks require shift, though.

**Comment by vladmoroz** [comment]
@marijnh I also use macOS, and my layout doesn't need shift to type backtick

**Comment by vladmoroz** [comment]
(Funnily enough, Cmd ` works when Caps Lock is on for me)

**Comment by drenther** [comment]
> @marijnh I also use macOS, and my layout doesn't need shift to type backtick

Same here. Sorry, Failed to mention it earlier. My keyboard doesn't require shift to use backticks.

**Comment by drenther** [comment]
> (Funnily enough, Cmd ` works when Caps Lock is on for me)

Just checked, it's the same for me as well. With Caps Lock on it seems to work fine.

**Comment by marijnh** [comment]
Ah, I see. Chrome seems to prevent Cmd-backtick presses from reaching the page. It works fine in Firefox and Safari, but no key event is fired in Chrome. I think that's a browser bug, rather than a library issue, and definitely not something ProseMirror can help.
