### ISSUE TITLE
Last update broke users

### ISSUE THREAD

**Issue by DamienCassou** [ProseMirror/prosemirror-example-setup#12]
Hi,

the last update of the package only mentions:

> Include TypeScript type declarations.

I understood that (and the absence of any major version number bump) as a sign that the new release is backward compatible. It is not though: renaming all files from .js to .ts means every import statement of users should be changed:

```diff
- import { openPrompt, TextField } from "prosemirror-example-setup/src/prompt.js";
+ import { openPrompt, TextField } from "prosemirror-example-setup/src/prompt.ts";
```

**Comment by marijnh** [comment]
Importing from `src` was never supported, sorry.

**Comment by DamienCassou** [comment]
Very good, thank you.
