### ISSUE TITLE
How to get this up and running?

### ISSUE THREAD

**Issue by kristiank** [ProseMirror/prosemirror-example-setup#13]
Hi!

First of all thanks for such an amazing project with really informative homepage, well written docs and guides and this example setup seems to hit the sweet spot for a setup that helps the user to start understand by tweaking and modifying.

But! For total newcomers to NPM and such – where is the one-liner to get this up and running locally? :flushing:

**Comment by marijnh** [comment]
There is no one liner—you're going to have to learn a bit about npm and bundlers to be able to integrate the library.
