### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by trusilosv** [ProseMirror/prosemirror-example-setup#18]
The type in the npm package and the repository are different. 
repositoty:  menuContent?:  MenuElement[][]
npm: menuContent?: MenuItem[][]

https://github.com/ProseMirror/prosemirror-example-setup/blob/43c1d95fb8669a86c3869338da00dd6bd974197d/src/index.ts#L59C1-L59C32

**Comment by marijnh** [comment]
Yes, that happens when patches are unreleased. I've tagged a 1.2.3 version.
